### ISSUE TITLE
Is it possible to use with AudioStreamPlayer3D?

### ISSUE THREAD

**Issue by nickpolet** [deadpixelsociety/gdsam-plugin#14] opened 2023-09-09 11:14 UTC
Using Godot 4.1 version with this, and can't seem to get any audio for an 3D audio player.

I noticed that using an AudioPlayer3D is specifically not mentioned in the readme, so i was wondering if there was a technical constraint with AudioPlayer3D?

**Comment by deadpixelsociety** [comment] 2023-09-14 13:49
@nickpolet Sorry for the delay on responding, but there should not be any constraint against using an AudioStreamPlayer3D. The plugin relies on using the shared interface between the different audio players, so as long as the methods and properties it's looking for exist on the object it shouldn't care. 

![image](https://github.com/deadpixelsociety/gdsam-plugin/assets/6668682/47d37d9f-43c9-4fdd-b5d5-2a2fc5a45511)

I'll check it out myself on my end later today to verify.

**Comment by deadpixelsociety** [comment] 2023-09-15 14:47
@nickpolet I setup a simple 3D scene test and got audio output from the plugin just fine through an AudioStreamPlayer3D. Due to how the 3D player works it does need to be in a 3D scene and you need to have an active 3D listener (either a camera or an AudioListener3D). Otherwise, it should work.

![image](https://github.com/deadpixelsociety/gdsam-plugin/assets/6668682/131dd1ba-6cbc-456e-939b-d1ada08ae764)

**Comment by deadpixelsociety** [comment] 2023-09-19 17:09
Plugin confirmed to work with AudioStreamPlayer3D. No issue here, so closing.

**Closed as completed by deadpixelsociety** 2023-09-19 17:09 UTC
Labels: question
